import React from 'react';


export const metadata = {
  title: "Apps Page | Keen-Keeper",
  description: "Generated by create next app",
};

const AppDetailsPage = async ({ params }) => {
    const { id } = await params
    console.log(id, "params");
    return (
        <div>
            This IS Id
        </div>
    );
};

export default AppDetailsPage;